# Generated by Django 4.2.6 on 2023-10-11 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0003_alter_point_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='name',
            field=models.CharField(default='Default Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='point',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levels.route'),
        ),
    ]
