# Generated by Django 4.2.6 on 2023-10-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0004_point_name_alter_point_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
