# Generated by Django 4.2.6 on 2023-10-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0005_point_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='point',
            name='hint',
            field=models.TextField(blank=True, null=True),
        ),
    ]
